version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg17  # Pre-built with pgvector
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin!123
      POSTGRES_DB: vectordb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: